from applications.serializers.ApplicationSerializer import ApplicationCreateSerializer
from applications.serializers.ApplicationSerializer import ApplicationPartiallyUpdateSerializer
from applications.serializers.ApplicationSerializer import ApplicationSerializer
from applications.serializers.CreateFirstApplicationSerializer import CreateFirstApplicationSerializer
from applications.serializers.ServiceSerializer import ServiceSerializer
