# Generated by Django 4.1.5 on 2023-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_city_name_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
