# Generated by Django 4.1.5 on 2023-01-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.servicecategory')),
            ],
        ),
    ]
