# Generated by Django 4.1.5 on 2023-01-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='applications.application'),
        ),
    ]
