# Generated by Django 4.1.5 on 2023-01-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_service_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_category',
            new_name='category',
        ),
    ]
