# Generated by Django 4.1.5 on 2023-01-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_rename_service_category_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstatus'),
        ),
    ]
