# Generated by Django 4.1.5 on 2023-01-18 07:23

import applications.models.ApplicationModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=applications.models.ApplicationModel.get_default_application_status, on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstatus'),
        ),
    ]
