# Generated by Django 4.1.5 on 2023-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
