# Generated by Django 4.1.5 on 2023-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_rename_parent_id_servicecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
