# Generated by Django 4.1.5 on 2023-01-25 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_service_date_from_alter_service_date_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_messagetype_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('application', 'manager', 'collocutor')},
        ),
    ]
